name: Pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.7

    - name: Install gmshairfoil2d with pip
      shell: bash -l {0}
      run: pip install -e .

    - name: Run pytest
      shell: bash -l {0}
      run: pytest -v
